### ISSUE TITLE
See if collaborators works

### ISSUE THREAD

**Issue by nataliesmith123** [nataliesmith123/squad-web#2]
(Can do via the cloud github interface). Navigate to content > authors > paul > index.md, edit the document. 

Add a sentence to the lorem ipsum content and commit that change.

**Comment by nataliesmith123** [comment]
Hi Paul just want to check if it's as easy for you to edit content as I think it is! Let me know if you can't figure it out / have any issues.

**Comment by pzivich** [comment]
Yes I can edit and push directly
